split:
	gcc -o secret_sharing secret_sharing.c
	./secret_sharing split 23
	
join:
	gcc -o secret_sharing secret_sharing.c
	./secret_sharing join 1,2 2,3 3,4
	
clean:
	rm -rf secret_sharing
	